#!/usr/bin/env bash
# This script configures an Nginx server to listen to port 80

ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Finally, starts Nginx
service nginx start
kill "$(pgrep 'nginx' | head -1)"
