#!/usr/bin/bash
#This bash script configures a container to run as nginx user
and configures it to listen on all active IPs on port 8080

# Replace the line containing '#user www-data' with 'user nginx' in the nginx.conf file
sed -i "s/#user www-data/user nginx/" /etc/nginx/nginx.conf

# Replace all instances of port 80 with port 8080 in the default site configuration
sed -i "s/80/8080/g" /etc/nginx/sites-available/default

# Change the permissions of the nginx.conf file to read and write for the owner, and read-only for others
chmod 644 /etc/nginx/nginx.conf

# Terminate any running apache2 processes
pkill apache2

# Restart the nginx service as the nginx user
sudo -u nginx service nginx restart
