#!/usr/bin/bash
# Same as 1-run_nginx_as_nginx file, just less lines of code. 
sed -i "s/#user www-data/user ngnix/" /etc/nginx/nginx.conf
sed -i -E "s/(listen.*)80 /\18080 /g" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx restart
